# Generated by Django 6.0.4 on 2026-06-20 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_otp_email_alter_otp_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="otp",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "OTP",
                "verbose_name_plural": "OTPs",
            },
        ),
        migrations.RemoveField(
            model_name="otp",
            name="attempts",
        ),
        migrations.RemoveField(
            model_name="otp",
            name="email",
        ),
        migrations.RemoveField(
            model_name="otp",
            name="purpose",
        ),
        migrations.AddField(
            model_name="otp",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="otp",
            name="code",
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name="otp",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="otps",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="otp",
            table="otp",
        ),
    ]
