# Generated by Django 6.0.4 on 2026-06-21 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_emailotp_options_rename_code_emailotp_otp_code_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailotp",
            options={},
        ),
        migrations.RemoveField(
            model_name="emailotp",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="emailotp",
            name="email",
        ),
        migrations.RemoveField(
            model_name="emailotp",
            name="expires_at",
        ),
        migrations.RemoveField(
            model_name="emailotp",
            name="is_verified",
        ),
        migrations.RemoveField(
            model_name="emailotp",
            name="otp_code",
        ),
        migrations.AlterModelTable(
            name="emailotp",
            table=None,
        ),
    ]
