# Generated by Django 6.0.4 on 2026-06-21 00:42

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_emailotp_options_remove_emailotp_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailotp",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="emailotp",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emailotp",
            name="email",
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emailotp",
            name="expires_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emailotp",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="emailotp",
            name="otp_code",
            field=models.CharField(default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        message="شماره موبایل معتبر نیست. باید با 09 شروع شود و 11 رقم باشد. مثال: 09123456789",
                        regex="^09[0-9]{9}$",
                    )
                ],
                verbose_name="شماره موبایل",
            ),
        ),
        migrations.AlterModelTable(
            name="emailotp",
            table="email_otp",
        ),
    ]
