# Generated by Django 6.0.4 on 2026-06-28 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_emailotp_options_emailotp_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="classRoom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.classroom",
            ),
        ),
    ]
